kube-prometheus-stack:

  grafana:
    enabled: false                  # using Grafana Cloud instead

  prometheus:
    prometheusSpec:
      scrapeInterval: "60s"
      evaluationInterval: "60s"
      retention: 3d

      remoteWrite:
        - url: https://prometheus-prod-32-prod-ca-east-0.grafana.net/api/prom/push
          basicAuth:
            username:
              name: grafana-cloud-secret
              key: username
            password:
              name: grafana-cloud-secret
              key: password

      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 300m
          memory: 512Mi
    
    ingress:
      enabled: true
      hosts:
        - homelab-prometheus.arguswatcher.net


  alertmanager:
    alertmanagerSpec:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 50m
          memory: 64Mi

  prometheusOperator:
    admissionWebhooks:
      enabled: false
      patch:
        enabled: false
    tls:
      enabled: false
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi

  kubeStateMetrics:
    enabled: true

  nodeExporter:
    enabled: true

  defaultRules:
    create: true
    rules:
      etcd: false
      kubeSchedulerAlerting: false
      kubeSchedulerRecording: false

  kube-state-metrics:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 50m
        memory: 64Mi

  prometheus-node-exporter:
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
      limits:
        cpu: 50m
        memory: 32Mi