kube-prometheus-stack:

  prometheus:
    prometheusSpec:
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 2000m
          memory: 2Gi

  # alertmanager:
  #   alertmanagerSpec:
  #     resources:
  #       requests:
  #         cpu: 10m
  #         memory: 32Mi
  #       limits:
  #         cpu: 50m
  #         memory: 64Mi

  # prometheusOperator:
  #   admissionWebhooks:
  #     enabled: true              # prevents apiserver crash
  #     patch:
  #       enabled: false
  #   tls:
  #     enabled: false
  #   resources:
  #     requests:
  #       cpu: 50m
  #       memory: 64Mi
  #     limits:
  #       cpu: 100m
  #       memory: 128Mi

  # kubeStateMetrics:
  #   enabled: true

  # nodeExporter:
  #   enabled: true

  # defaultRules:
  #   create: true
  #   rules:
  #     etcd: false
  #     kubeSchedulerAlerting: false
  #     kubeSchedulerRecording: false

  # kube-state-metrics:
  #   resources:
  #     requests:
  #       cpu: 10m
  #       memory: 32Mi
  #     limits:
  #       cpu: 50m
  #       memory: 64Mi

  # prometheus-node-exporter:
  #   resources:
  #     requests:
  #       cpu: 10m
  #       memory: 16Mi
  #     limits:
  #       cpu: 50m
  #       memory: 32Mi

  grafana:
    enabled: true
    adminPassword: "changeme123"

    # resources:
    #   requests:
    #     memory: 256Mi
    #     cpu: 100m
    #   limits:
    #     memory: 512Mi
    #     cpu: 500m

  #   initChownData:
  #     enabled: false   

  #   persistence:
  #     enabled: true
  #     storageClassName: standard
  #     size: 5Gi

  #   ingress:
  #     enabled: true
  #     ingressClassName: nginx
  #     hosts:
  #       - grafana.local