kube-prometheus-stack:
  grafana:
    enabled: true
    adminPassword: "prom-password"
    persistence:
      enabled: true
      storageClassName: standard
      size: 5Gi
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - grafana.local
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
        
  prometheus:
    server:
      persistentVolume:
        enabled: true
        storageClassName: standard
        size: 10Gi
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - prometheus.local
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1Gi

  alertmanager:
    persistentVolume:
      enabled: true
      storageClassName: standard
      size: 2Gi