apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab

  source:
    repoURL: https://github.com/simonangel-fong/Homelab-Prometheus-Grafana.git
    targetRevision: main
    path: manifests
    helm:
      releaseName: prometheus-grafana
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: monitor

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
